<?php

namespace ContainerY19ECqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xpf6FhuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xpf6Fhu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xpf6Fhu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'classesRepository' => ['privates', 'App\\Repository\\ClassesRepository', 'getClassesRepositoryService', true],
            'entityManager' => ['privates', '.errored..service_locator.xpf6Fhu.Doctrine\\ORM\\EntityManager', NULL, 'Cannot autowire service ".service_locator.xpf6Fhu": it references class "Doctrine\\ORM\\EntityManager" but no such service exists. Try changing the type-hint to "Doctrine\\ORM\\EntityManagerInterface" instead.'],
            'sortsRepository' => ['privates', 'App\\Repository\\SortsRepository', 'getSortsRepositoryService', true],
        ], [
            'classesRepository' => 'App\\Repository\\ClassesRepository',
            'entityManager' => 'Doctrine\\ORM\\EntityManager',
            'sortsRepository' => 'App\\Repository\\SortsRepository',
        ]);
    }
}
