<?php

namespace ContainerY19ECqS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDnd35SortsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K6bU1Y0.App\Entity\Dnd35Sorts' shared service.
     *
     * @return \App\Entity\Dnd35Sorts
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.K6bU1Y0": it references class "App\\Entity\\Dnd35Sorts" but no such service exists.');
    }
}
