<?php

namespace ContainerCwxHVAP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D_IAsR6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D.IAsR6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D.IAsR6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dnd35Don' => ['privates', '.errored..service_locator.D.IAsR6.App\\Entity\\Dnd35Dons', NULL, 'Cannot autowire service ".service_locator.D.IAsR6": it references class "App\\Entity\\Dnd35Dons" but no such service exists.'],
            'donsRepository' => ['privates', 'App\\Repository\\DonsRepository', 'getDonsRepositoryService', true],
        ], [
            'dnd35Don' => 'App\\Entity\\Dnd35Dons',
            'donsRepository' => 'App\\Repository\\DonsRepository',
        ]);
    }
}
