<?php

namespace ContainerCwxHVAP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C2uCutVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c2uCutV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c2uCutV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dnd35Sort' => ['privates', '.errored..service_locator.c2uCutV.App\\Entity\\Dnd35Sorts', NULL, 'Cannot autowire service ".service_locator.c2uCutV": it references class "App\\Entity\\Dnd35Sorts" but no such service exists.'],
        ], [
            'dnd35Sort' => 'App\\Entity\\Dnd35Sorts',
        ]);
    }
}
