<?php

namespace ContainerCwxHVAP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TSfQRD2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tSfQRD2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tSfQRD2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'classesRepository' => ['privates', 'App\\Repository\\ClassesRepository', 'getClassesRepositoryService', true],
            'sortsRepository' => ['privates', 'App\\Repository\\SortsRepository', 'getSortsRepositoryService', true],
        ], [
            'classesRepository' => 'App\\Repository\\ClassesRepository',
            'sortsRepository' => 'App\\Repository\\SortsRepository',
        ]);
    }
}
