<?php

namespace ContainerCwxHVAP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDnd35Dons2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.joixzhu.App\Entity\Dnd35Dons' shared service.
     *
     * @return \App\Entity\Dnd35Dons
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.joixzhu": it references class "App\\Entity\\Dnd35Dons" but no such service exists.');
    }
}
