<?php

namespace ContainerCwxHVAP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDnd35RacesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.En51Kqp.App\Entity\Dnd35Races' shared service.
     *
     * @return \App\Entity\Dnd35Races
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.En51Kqp": it references class "App\\Entity\\Dnd35Races" but no such service exists.');
    }
}
