<?php

namespace ContainerYzsGRte;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GEPnQmVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GEPnQmV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GEPnQmV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'class' => ['privates', '.errored..service_locator.GEPnQmV.App\\Entity\\Classes', NULL, 'Cannot autowire service ".service_locator.GEPnQmV": it references class "App\\Entity\\Classes" but no such service exists.'],
            'classesRepository' => ['privates', 'App\\Repository\\ClassesRepository', 'getClassesRepositoryService', true],
        ], [
            'class' => 'App\\Entity\\Classes',
            'classesRepository' => 'App\\Repository\\ClassesRepository',
        ]);
    }
}
