<?php

namespace ContainerYzsGRte;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSortsControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\SortsController' shared autowired service.
     *
     * @return \App\Controller\SortsController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/SortsController.php';

        $container->services['App\\Controller\\SortsController'] = $instance = new \App\Controller\SortsController();

        $instance->setContainer(($container->privates['.service_locator.GNc8e5B'] ?? $container->load('get_ServiceLocator_GNc8e5BService'))->withContext('App\\Controller\\SortsController', $container));

        return $instance;
    }
}
