<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNroMgxV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNroMgxV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNroMgxV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNroMgxV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNroMgxV\App_KernelDevDebugContainer([
    'container.build_hash' => 'NroMgxV',
    'container.build_id' => 'a5fb7cc1',
    'container.build_time' => 1696326301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNroMgxV');
