<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKGyKAfD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKGyKAfD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKGyKAfD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKGyKAfD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKGyKAfD\App_KernelDevDebugContainer([
    'container.build_hash' => 'KGyKAfD',
    'container.build_id' => '2b0ebd7d',
    'container.build_time' => 1695826119,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKGyKAfD');
