<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFj8Vi4q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFj8Vi4q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFj8Vi4q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFj8Vi4q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFj8Vi4q\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fj8Vi4q',
    'container.build_id' => '2063808f',
    'container.build_time' => 1692043315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFj8Vi4q');
